version: '3'

services:  
  django:
    build: .
    container_name: esctop-django
    expose:
      - 8000
    command: 
      - bash 
      - -c 
      - |
        python manage.py migrate
        python manage.py collectstatic --noinput
        gunicorn --bind 0.0.0.0:8000 sisos.wsgi
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nginx.entrypoints=web,websecure'
      - 'traefik.http.routers.nginx.rule=Host(`SEU DOMINIO`)'
      - 'traefik.http.routers.nginx.tls=true'     
      - 'traefik.http.routers.nginx.tls.certresolver=production' 

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      - "8080:8080"  # Don't do this in production!
    volumes:
      - ./traefik/:/etc/traefik/
      - traefik-ssl-certs:/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  traefik-ssl-certs:
    driver: local