# Generated by Django 3.0.5 on 2020-04-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Cliente',
        ),
    ]
