# Generated by Django 3.0.5 on 2020-05-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20200425_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.DeleteModel(
            name='CPF',
        ),
    ]
