# Generated by Django 3.0.5 on 2020-05-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20200518_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_da_mae',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_do_pai',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Pai'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='anotacoes',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Anotações'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
