# Generated by Django 3.0.5 on 2020-05-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_auto_20200519_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='num_telefone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='celular1',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='celular 1'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='celular2',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='celular 2'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato1',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Contato 1'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato2',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Contato 2'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sacado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sacado'),
        ),
    ]
