# Generated by Django 3.0.6 on 2020-05-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_auto_20200519_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sacado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sacado'),
        ),
    ]
