# Generated by Django 3.0.6 on 2020-05-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_auto_20200519_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_nasc',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
