# Generated by Django 3.0.6 on 2020-05-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_auto_20200519_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='anotacoes',
            field=models.TextField(max_length=200, verbose_name='Anotações'),
        ),
    ]
