# Generated by Django 3.0.6 on 2020-05-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_auto_20200520_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='naturalidade'),
        ),
    ]
