# Generated by Django 3.0.6 on 2020-05-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_cliente_naturalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular1',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='celular 1'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular2',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='celular 2'),
        ),
    ]
