# Generated by Django 3.0.6 on 2020-05-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_auto_20200522_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ibge',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='IBGE'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular1',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='celular 1'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular2',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='celular 2'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato 1'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato 2'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rua',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Rua'),
        ),
    ]
