# Generated by Django 3.0.6 on 2020-05-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0017_auto_20200524_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ibge_trabalho',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero_casa_trabalho',
        ),
        migrations.AddField(
            model_name='cliente',
            name='agencia',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='banco',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='conta',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='obs_bancaria',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referencia_trabalho',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referência'),
        ),
    ]
