# Generated by Django 3.0.6 on 2020-06-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0018_auto_20200524_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='anotacoes',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Anotações'),
        ),
    ]
