# Generated by Django 3.0.6 on 2020-06-02 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0019_auto_20200601_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avalista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avalista', models.CharField(blank=True, max_length=11, null=True, verbose_name='Avalista')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='avalista',
            field=models.ForeignKey(blank=True, max_length=11, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.Avalista'),
        ),
    ]
