# Generated by Django 3.0.6 on 2020-06-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0020_auto_20200602_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='avalista',
            name='cpf_avalista',
            field=models.CharField(default='SOME STRING', max_length=20, unique=True, verbose_name='CPF do Avalista'),
        ),
    ]
