# Generated by Django 3.0.6 on 2020-06-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0021_avalista_cpf_avalista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalista',
            name='cpf_avalista',
            field=models.CharField(max_length=20, unique=True, verbose_name='CPF do Avalista'),
        ),
    ]
