# Generated by Django 3.0.6 on 2020-06-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0022_auto_20200602_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalista',
            name='avalista',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Avalista'),
        ),
    ]
