# Generated by Django 3.0.6 on 2020-06-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0023_auto_20200602_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avalista',
            options={'ordering': ('avalista',)},
        ),
    ]
