# Generated by Django 3.0.6 on 2020-06-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0025_auto_20200607_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ibge',
        ),
    ]
