# Generated by Django 3.0.6 on 2020-06-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0026_remove_cliente_ibge'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ibge',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='IBGE'),
        ),
    ]
