# Generated by Django 3.0.6 on 2020-06-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0029_auto_20200607_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='orgao_expedidor',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Orgão Expedidor'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Estado Civil'),
        ),
    ]
