# Generated by Django 3.0.6 on 2020-06-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0030_auto_20200607_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='avalista',
            name='bairro',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='cidade',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='data_nasc_avalista',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='estado_civil_avalista',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='naturalidade_avalista',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='naturalidade'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Nº '),
        ),
        migrations.AddField(
            model_name='avalista',
            name='orgao_expedidor_avalista',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Org Exp'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='rg_avalista',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='rua',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='orgao_expedidor',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Org Exp'),
        ),
    ]
