# Generated by Django 3.0.7 on 2020-06-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0031_auto_20200608_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_nasc',
            field=models.DateField(max_length=8, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(max_length=15, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='naturalidade',
            field=models.CharField(max_length=15, null=True, verbose_name='naturalidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_da_mae',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='orgao_expedidor',
            field=models.CharField(max_length=15, null=True, verbose_name='Org Exp'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(max_length=20, null=True, verbose_name='RG'),
        ),
    ]
