# Generated by Django 3.0.7 on 2020-06-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0032_auto_20200623_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(max_length=40, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(max_length=40, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_casa',
            field=models.CharField(max_length=5, null=True, verbose_name='Nº '),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rua',
            field=models.CharField(max_length=60, null=True, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='uf',
            field=models.CharField(max_length=2, null=True, verbose_name='Estado'),
        ),
    ]
