# Generated by Django 3.0.7 on 2020-07-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0001_initial'),
        ('cliente', '0033_auto_20200623_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='avalista',
            field=models.ForeignKey(blank=True, max_length=11, null=True, on_delete=django.db.models.deletion.PROTECT, to='avalista.Avalista'),
        ),
        migrations.DeleteModel(
            name='Avalista',
        ),
    ]
