# Generated by Django 3.0.7 on 2020-07-17 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0034_auto_20200712_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCopia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_copia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
            options={
                'ordering': ('cliente_copia',),
            },
        ),
    ]
