# Generated by Django 3.0.7 on 2020-07-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0036_auto_20200717_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliente_copia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
    ]
