# Generated by Django 3.0.7 on 2020-07-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0037_cliente_cliente_copia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClienteCopia',
        ),
    ]
