# Generated by Django 3.0.7 on 2020-07-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0038_delete_clientecopia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='avalista',
        ),
    ]
