# Generated by Django 3.0.7 on 2020-07-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0039_remove_cliente_avalista'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='naturalidade',
            field=models.CharField(max_length=15, null=True, verbose_name='Naturalidade'),
        ),
    ]
