# Generated by Django 3.0.7 on 2020-07-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0040_auto_20200723_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_copia',
            new_name='fiador',
        ),
    ]
