# Generated by Django 3.0.7 on 2020-09-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200909_1739'),
        ('cliente', '0045_remove_cliente_obs_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='banco',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Dados_bancarios'),
        ),
    ]
