# Generated by Django 3.0.7 on 2020-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0050_auto_20200910_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='anotacoes_trabalho',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Anotações'),
        ),
    ]
