# Generated by Django 3.0.7 on 2020-09-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0052_cliente_whatsapp_trabalho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='anotacoes_trabalho',
        ),
        migrations.AddField(
            model_name='cliente',
            name='obs_trabalho',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp_trabalho',
            field=models.BooleanField(default=True, verbose_name='Observações'),
        ),
    ]
