# Generated by Django 3.0.7 on 2020-09-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0053_auto_20200911_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp',
            field=models.BooleanField(default=True, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp_trabalho',
            field=models.BooleanField(default=True, verbose_name='Whatsapp'),
        ),
    ]
