# Generated by Django 3.0.7 on 2020-09-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0054_auto_20200911_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='whatsapp1',
            field=models.BooleanField(default=True, verbose_name='Whatsapp'),
        ),
    ]
