# Generated by Django 3.0.7 on 2020-09-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0055_cliente_whatsapp1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='whatsapp',
            new_name='whatsapp1_trabalho',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='whatsapp_trabalho',
            new_name='whatsapp2',
        ),
        migrations.AddField(
            model_name='cliente',
            name='whatsapp2_trabalho',
            field=models.BooleanField(default=True, verbose_name='Whatsapp'),
        ),
    ]
