# Generated by Django 3.0.7 on 2020-09-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0057_auto_20200911_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ref1_contato',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ref1_nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ref1_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parentesco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ref2_contato',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ref2_nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ref2_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parentesco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ref3_contato',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ref3_nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ref3_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parentesco'),
        ),
    ]
