# Generated by Django 3.0.7 on 2020-09-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0058_auto_20200921_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='naturalidade',
            field=models.CharField(max_length=20, null=True, verbose_name='Naturalidade'),
        ),
    ]
