# Generated by Django 3.0.7 on 2020-09-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0059_auto_20200929_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero_casa_trabalho',
            field=models.CharField(max_length=5, null=True, verbose_name='Nº '),
        ),
    ]
