# Generated by Django 3.0.7 on 2020-09-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0060_cliente_numero_casa_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Nº '),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_casa_trabalho',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Nº '),
        ),
    ]
