# Generated by Django 3.0.7 on 2020-10-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0063_auto_20201013_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='conjuge_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF Cônjuge'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='conjuge_nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome Cônjuge'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='conjuge_telefone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Contato Cônjuge'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('CS', 'CASADO'), ('SO', 'SOLTEIRO'), ('DV', 'DIVORCIADO'), ('VI', 'VIÚVO')], max_length=15, null=True, verbose_name='Estado Civil'),
        ),
    ]
