# Generated by Django 3.0.7 on 2020-10-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0064_auto_20201015_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Estado Civil'),
        ),
    ]
