# Generated by Django 3.0.7 on 2022-03-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0066_auto_20210216_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pix',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave PIX'),
        ),
    ]
