# Generated by Django 3.0.7 on 2022-03-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0067_cliente_pix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pix',
        ),
    ]
