# Generated by Django 3.0.7 on 2022-03-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220315_1529'),
        ('cliente', '0068_remove_cliente_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='chave_pix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Chave_PIX'),
        ),
    ]
