# Generated by Django 3.0.7 on 2022-03-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220315_1529'),
        ('cliente', '0069_cliente_chave_pix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='chave_pix',
        ),
        migrations.AddField(
            model_name='cliente',
            name='chave_pix',
            field=models.ManyToManyField(blank=True, null=True, to='core.Chave_PIX'),
        ),
    ]
