# Generated by Django 3.0.7 on 2022-03-15 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220315_1544'),
        ('cliente', '0071_remove_cliente_chave_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_de_chave_pix',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Chave_PIX'),
        ),
    ]
