# Generated by Django 3.0.7 on 2022-03-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0072_cliente_tipo_de_chave_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Chave Pix'),
        ),
    ]
