# Generated by Django 3.0.7 on 2022-03-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220315_1547'),
        ('cliente', '0073_cliente_chave_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave Pix'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_de_chave_pix',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Chave_PIX'),
        ),
    ]
