# Generated by Django 3.0.7 on 2022-08-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0074_auto_20220315_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fiador_inativo',
            field=models.BooleanField(default=False, verbose_name='Fiador inativo'),
        ),
    ]
