# Generated by Django 3.0.7 on 2022-10-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0075_cliente_fiador_inativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp1',
            field=models.BooleanField(default=False, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp1_trabalho',
            field=models.BooleanField(default=False, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp2',
            field=models.BooleanField(default=False, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp2_trabalho',
            field=models.BooleanField(default=False, verbose_name='Whatsapp'),
        ),
    ]
