# Generated by Django 3.0.7 on 2022-11-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0076_auto_20221014_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
