# Generated by Django 3.0.7 on 2022-11-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0077_cliente_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='upload',
        ),
        migrations.AddField(
            model_name='cliente',
            name='file_identification_document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Documento de identificação'),
        ),
    ]
