# Generated by Django 3.0.7 on 2022-11-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0078_auto_20221128_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='file_proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Comprovante de residência'),
        ),
    ]
