# Generated by Django 3.0.7 on 2022-11-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0079_cliente_file_proof_of_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='file_identification_document',
            new_name='identification_document',
        ),
    ]
