# Generated by Django 3.0.7 on 2022-11-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0080_auto_20221129_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='file_proof_of_address',
            new_name='proof_of_address',
        ),
    ]
