# Generated by Django 3.0.7 on 2020-07-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=50, verbose_name='Nome Fantasia')),
                ('fundacao', models.DateField(max_length=8, null=True, verbose_name='Fundação')),
                ('forma_constituicao', models.CharField(max_length=50, verbose_name='Forma Constituição')),
                ('inscricao_estadual', models.CharField(max_length=50, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(max_length=50, verbose_name='Inscrição Municipal')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
            ],
        ),
    ]
