# Generated by Django 3.0.7 on 2020-07-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Cliente_cnpj',
        ),
    ]
