# Generated by Django 3.0.7 on 2020-07-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0003_auto_20200711_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='forma_constituicao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma Constituição'),
        ),
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='fundacao',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='Fundação'),
        ),
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal'),
        ),
    ]
