# Generated by Django 3.0.6 on 2020-07-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0004_auto_20200711_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='bairro',
            field=models.CharField(max_length=40, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='cep',
            field=models.CharField(max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='cidade',
            field=models.CharField(max_length=40, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='numero_casa',
            field=models.CharField(max_length=5, null=True, verbose_name='Nº '),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ponto de Referencia'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rua',
            field=models.CharField(max_length=60, null=True, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='uf',
            field=models.CharField(max_length=2, null=True, verbose_name='Estado'),
        ),
    ]
