# Generated by Django 3.0.6 on 2020-07-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0034_auto_20200712_1219'),
        ('cliente_cnpj', '0006_auto_20200715_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='representante',
            field=models.ForeignKey(blank=True, max_length=11, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.Cliente'),
        ),
    ]
