# Generated by Django 3.0.7 on 2020-07-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0008_cliente_cnpj_anotacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='razao_social',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome Fantasia'),
        ),
    ]
