# Generated by Django 3.0.7 on 2020-07-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0009_cliente_cnpj_razao_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='razao_social',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Razão Social'),
        ),
    ]
