# Generated by Django 3.0.7 on 2020-07-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0010_auto_20200722_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
