# Generated by Django 3.0.7 on 2020-07-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0012_auto_20200722_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='cnpj',
            field=models.CharField(max_length=26, unique=True, verbose_name='CNPJ'),
        ),
    ]
