# Generated by Django 3.0.7 on 2020-08-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0016_auto_20200723_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente_cnpj',
            name='anotacoes',
        ),
        migrations.RemoveField(
            model_name='cliente_cnpj',
            name='representante',
        ),
    ]
