# Generated by Django 3.0.7 on 2020-08-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0017_auto_20200811_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_bairro',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_celular1',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='celular 1'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_celular2',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='celular 2'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_cidade',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_contato1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato 1'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_numero_casa',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Nº '),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_ponto_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ponto de Referencia'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_rua',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
    ]
