# Generated by Django 3.0.7 on 2020-08-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0018_auto_20200811_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_agencia',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_banco',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_conta',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_obs_bancaria',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Observações'),
        ),
    ]
