# Generated by Django 3.0.7 on 2020-08-18 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0007_avalista_fiador_copia'),
        ('cliente_cnpj', '0019_auto_20200814_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='fiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avalista.Avalista'),
        ),
    ]
