# Generated by Django 3.0.7 on 2020-08-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0020_cliente_cnpj_fiador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_cnpj_aval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aval_razao_social', models.CharField(blank=True, max_length=50, null=True, verbose_name='ava_Razão Social')),
                ('aval_nome_fantasia', models.CharField(max_length=50, verbose_name='ava_Nome Fantasia')),
                ('aval_cnpj', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='ava_CNPJ')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cliente_cnpj',
            options={'ordering': ('razao_social',)},
        ),
        migrations.RemoveField(
            model_name='cliente_cnpj',
            name='fiador',
        ),
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='rep_banco',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Re-Banco'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='aval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente_cnpj.Cliente_cnpj_aval'),
        ),
    ]
