# Generated by Django 3.0.7 on 2020-08-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0008_delete_teste'),
        ('cliente_cnpj', '0021_auto_20200821_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente_cnpj',
            name='aval',
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='fiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avalista.Avalista'),
        ),
        migrations.DeleteModel(
            name='Cliente_cnpj_aval',
        ),
    ]
