# Generated by Django 3.0.7 on 2020-08-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0022_auto_20200825_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='ref1_contato1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='ref1_nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
    ]
