# Generated by Django 3.0.7 on 2020-08-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0023_auto_20200826_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='ref1_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parentesco'),
        ),
    ]
