# Generated by Django 3.0.7 on 2020-08-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0024_cliente_cnpj_ref1_parentesco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente_cnpj',
            old_name='ref1_contato1',
            new_name='ref1_contato',
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='ref2_contato',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='ref2_nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='ref2_parentesco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parentesco'),
        ),
    ]
