# Generated by Django 3.0.7 on 2020-08-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0026_auto_20200827_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
    ]
