# Generated by Django 3.0.7 on 2020-08-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0027_cliente_cnpj_rep_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='ref1_contato',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='ref2_contato',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Contato'),
        ),
    ]
