# Generated by Django 3.0.7 on 2020-08-29 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0010_auto_20200826_0737'),
        ('cliente_cnpj', '0028_auto_20200827_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='fiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='avalista.Avalista'),
        ),
    ]
