# Generated by Django 3.0.7 on 2020-09-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0029_auto_20200829_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_estado_civil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_nacionalidade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_org_emissor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Orgão Emissor'),
        ),
    ]
