# Generated by Django 3.0.7 on 2020-09-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0030_auto_20200901_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='rep_uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
