# Generated by Django 3.0.7 on 2020-09-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0031_auto_20200909_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='uf',
            field=models.CharField(max_length=2, null=True, verbose_name='UF'),
        ),
    ]
