# Generated by Django 3.0.7 on 2020-09-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0032_auto_20200909_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente_cnpj',
            old_name='rep_org_emissor',
            new_name='rep_orgao_emissor',
        ),
    ]
