# Generated by Django 3.0.7 on 2020-09-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_dados_bancarios'),
        ('cliente_cnpj', '0037_auto_20200910_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='tipo_de_conta',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Tipo_de_conta'),
        ),
    ]
