# Generated by Django 3.0.7 on 2020-09-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0039_auto_20200910_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente_cnpj',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_whatsapp1',
            field=models.BooleanField(default=True, verbose_name='Whatsapp'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_whatsapp2',
            field=models.BooleanField(default=True, verbose_name='Whatsapp'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='whatsapp1',
            field=models.BooleanField(default=True, verbose_name='Whatsapp'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='whatsapp2',
            field=models.BooleanField(default=True, verbose_name='Whatsapp'),
        ),
    ]
