# Generated by Django 3.0.7 on 2020-09-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0040_auto_20200911_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Nº '),
        ),
    ]
