# Generated by Django 3.0.7 on 2020-10-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0041_auto_20200930_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente_cnpj',
            name='forma_constituicao',
        ),
    ]
