# Generated by Django 3.0.7 on 2020-10-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0042_remove_cliente_cnpj_forma_constituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_data_nasc',
            field=models.DateField(max_length=8, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
