# Generated by Django 3.0.7 on 2020-10-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0043_cliente_cnpj_rep_data_nasc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_naturalidade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='rep_data_nasc',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
