# Generated by Django 3.0.7 on 2020-10-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0044_auto_20201015_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_conjuge_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF Cônjuge'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_conjuge_nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome Cônjuge'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_conjuge_telefone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Contato Cônjuge'),
        ),
    ]
