# Generated by Django 3.0.7 on 2020-11-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0046_auto_20201016_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='rep_celular1',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Celular 1'),
        ),
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='rep_celular2',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Celular 2'),
        ),
    ]
