# Generated by Django 3.0.7 on 2022-01-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0047_auto_20201102_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_mae',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='cliente_cnpj',
            name='rep_pai',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Pai'),
        ),
    ]
