# Generated by Django 3.0.7 on 2022-08-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0049_auto_20220315_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_cnpj',
            name='fiador_inativo',
            field=models.BooleanField(default=False, verbose_name='Fiador inativo'),
        ),
    ]
