# Generated by Django 3.0.7 on 2022-12-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0050_cliente_cnpj_fiador_inativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='razao_social',
            field=models.CharField(max_length=50, null=True, verbose_name='Razão Social'),
        ),
    ]
