# Generated by Django 4.1.3 on 2022-12-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0051_auto_20221202_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
