# Generated by Django 4.1.3 on 2024-01-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0052_alter_cliente_cnpj_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_cnpj',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave Pix'),
        ),
    ]
