# Generated by Django 3.0.7 on 2021-08-10 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_delete_dados_bancarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato 1')),
                ('whatsapp', models.BooleanField(default=True, verbose_name='Whatsapp')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=20, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, null=True, verbose_name='RG')),
                ('orgao_emissor', models.CharField(max_length=15, null=True, verbose_name='Orgão Emissor')),
                ('data_nasc', models.DateField(max_length=8, null=True, verbose_name='Data de Nascimento')),
                ('naturalidade', models.CharField(max_length=20, null=True, verbose_name='Naturalidade')),
                ('nacionalidade', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nacionalidade')),
                ('estado_civil', models.CharField(blank=True, max_length=15, null=True, verbose_name='Estado Civil')),
                ('conjuge_nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome Cônjuge')),
                ('conjuge_cpf', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF Cônjuge')),
                ('conjuge_telefone', models.CharField(blank=True, max_length=17, null=True, verbose_name='Contato Cônjuge')),
                ('nome_da_mae', models.CharField(max_length=50, null=True, verbose_name='Nome da Mãe')),
                ('nome_do_pai', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da Pai')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10, null=True, verbose_name='CEP')),
                ('rua', models.CharField(max_length=60, null=True, verbose_name='Rua')),
                ('bairro', models.CharField(max_length=40, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=40, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, null=True, verbose_name='UF')),
                ('numero_casa', models.CharField(blank=True, max_length=5, null=True, verbose_name='Nº ')),
                ('ponto_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ponto de Referencia')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
            ],
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parentesco')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credcoop.Contato')),
            ],
        ),
        migrations.CreateModel(
            name='LocalDeTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome Fantasia')),
                ('referencia_trabalho', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ponto de Referencia')),
                ('obs_trabalho', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observações')),
                ('contato', models.ManyToManyField(to='credcoop.Contato')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credcoop.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_operacao', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº operação')),
                ('agencia', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº agência')),
                ('conta', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº conta')),
                ('banco', models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Banco')),
                ('tipo_de_conta', models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Tipo_de_conta')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteCredcoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.ManyToManyField(related_name='Contato', to='credcoop.Contato')),
                ('dados_bancarios', models.ManyToManyField(to='credcoop.DadosBancarios')),
                ('dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credcoop.DadosPessoais')),
                ('endereco', models.ManyToManyField(related_name='Endereco', to='credcoop.Endereco')),
                ('fiador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credcoop.ClienteCredcoop')),
                ('local_de_trabalho', models.ManyToManyField(to='credcoop.LocalDeTrabalho')),
            ],
        ),
    ]
