# Generated by Django 3.0.5 on 2020-04-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='produto',
            field=models.CharField(max_length=100, unique=True, verbose_name='Produto'),
        ),
    ]
