# Generated by Django 3.0.7 on 2020-07-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avalista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avalista', models.CharField(blank=True, max_length=50, null=True, verbose_name='Avalista')),
                ('cpf_avalista', models.CharField(max_length=20, unique=True, verbose_name='CPF do Avalista')),
                ('rg_avalista', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('orgao_expedidor_avalista', models.CharField(blank=True, max_length=15, null=True, verbose_name='Org Exp')),
                ('data_nasc_avalista', models.DateField(blank=True, max_length=8, null=True, verbose_name='Data de Nascimento')),
                ('naturalidade_avalista', models.CharField(blank=True, max_length=15, null=True, verbose_name='naturalidade')),
                ('estado_civil_avalista', models.CharField(blank=True, max_length=15, null=True, verbose_name='Estado Civil')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('rua', models.CharField(blank=True, max_length=60, null=True, verbose_name='Rua')),
                ('bairro', models.CharField(blank=True, max_length=40, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=40, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('numero_casa', models.CharField(blank=True, max_length=5, null=True, verbose_name='Nº ')),
            ],
            options={
                'ordering': ('avalista',),
            },
        ),
    ]
