# Generated by Django 3.0.7 on 2020-08-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste', models.CharField(blank=True, max_length=50, null=True, verbose_name='Avalista')),
                ('cpf_teste', models.CharField(max_length=20, unique=True, verbose_name='CPF do Avalista')),
                ('rg_teste', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
            ],
        ),
    ]
