# Generated by Django 3.0.7 on 2020-08-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0002_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='cpf_teste',
            field=models.CharField(max_length=20, unique=True, verbose_name='CPF do Teste'),
        ),
        migrations.AlterField(
            model_name='teste',
            name='rg_teste',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG do Teste'),
        ),
        migrations.AlterField(
            model_name='teste',
            name='teste',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teste'),
        ),
    ]
