# Generated by Django 3.0.7 on 2020-08-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0003_auto_20200810_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avalista',
            options={'ordering': ('fiador_nome',)},
        ),
        migrations.RenameField(
            model_name='avalista',
            old_name='bairro',
            new_name='fiador_bairro',
        ),
        migrations.RenameField(
            model_name='avalista',
            old_name='cep',
            new_name='fiador_cep',
        ),
        migrations.RemoveField(
            model_name='avalista',
            name='avalista',
        ),
        migrations.RemoveField(
            model_name='avalista',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='avalista',
            name='cpf_avalista',
        ),
        migrations.RemoveField(
            model_name='avalista',
            name='data_nasc_avalista',
        ),
        migrations.RemoveField(
            model_name='avalista',
            name='estado_civil_avalista',
        ),
        migrations.RemoveField(
            model_name='avalista',
            name='naturalidade_avalista',
        ),
        migrations.RemoveField(
            model_name='avalista',
            name='numero_casa',
        ),
        migrations.RemoveField(
            model_name='avalista',
            name='orgao_expedidor_avalista',
        ),
        migrations.RemoveField(
            model_name='avalista',
            name='rg_avalista',
        ),
        migrations.RemoveField(
            model_name='avalista',
            name='rua',
        ),
        migrations.RemoveField(
            model_name='avalista',
            name='uf',
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_agencia',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_banco',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_celular1',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='celular 1'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_celular2',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='celular 2'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_cidade',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_conta',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_contato1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato 1'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_l',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_numero_casa',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Nº '),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_obs_bancaria',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_ponto_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ponto de Referencia'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_rua',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
    ]
