# Generated by Django 3.0.7 on 2020-08-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0004_auto_20200814_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avalista',
            old_name='fiador_l',
            new_name='fiador_email',
        ),
    ]
