# Generated by Django 3.0.7 on 2020-08-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0007_avalista_fiador_copia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
