# Generated by Django 3.0.7 on 2020-09-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0010_auto_20200826_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='avalista',
            name='fiador_org_emissor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Orgão Emissor'),
        ),
    ]
