# Generated by Django 3.0.7 on 2020-09-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0011_avalista_fiador_org_emissor'),
    ]

    operations = [
        migrations.AddField(
            model_name='avalista',
            name='fiador_estado_civil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='fiador_nacionalidade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nacionalidade'),
        ),
    ]
