# Generated by Django 3.0.7 on 2020-09-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0012_auto_20200901_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='avalista',
            name='fiador_complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='avalista',
            name='fiador_uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
