# Generated by Django 3.0.7 on 2020-09-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200909_1739'),
        ('avalista', '0015_remove_avalista_fiador_obs_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalista',
            name='fiador_banco',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Dados_bancarios'),
        ),
    ]
