# Generated by Django 3.0.7 on 2020-09-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0016_auto_20200909_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avalista',
            old_name='fiador_banco',
            new_name='banco',
        ),
    ]
