# Generated by Django 3.0.7 on 2020-09-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0017_auto_20200909_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='avalista',
            name='whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
