# Generated by Django 3.0.7 on 2020-09-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0020_avalista_tipo_de_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='avalista',
            name='fiador_n_operacao',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº operação'),
        ),
    ]
