# Generated by Django 3.0.7 on 2020-09-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0021_avalista_fiador_n_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalista',
            name='fiador_agencia',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº agência'),
        ),
        migrations.AlterField(
            model_name='avalista',
            name='fiador_conta',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº conta'),
        ),
    ]
