# Generated by Django 3.0.7 on 2020-09-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0022_auto_20200910_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avalista',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='avalista',
            name='whatsapp1',
            field=models.BooleanField(default=True, verbose_name='Whatsapp'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='whatsapp2',
            field=models.BooleanField(default=True, verbose_name='Whatsapp'),
        ),
    ]
