# Generated by Django 3.0.7 on 2020-09-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0023_auto_20200911_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='avalista',
            name='fiador_naturalidade',
            field=models.CharField(max_length=20, null=True, verbose_name='Naturalidade'),
        ),
    ]
