# Generated by Django 3.0.7 on 2021-02-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0025_avalista_fiador_data_nasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalista',
            name='fiador_nome',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome'),
        ),
    ]
