# Generated by Django 3.0.7 on 2021-02-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0026_auto_20210216_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalista',
            name='fiador_cep',
            field=models.CharField(max_length=10, null=True, verbose_name='CEP'),
        ),
    ]
