# Generated by Django 4.1.3 on 2022-12-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalista', '0029_auto_20220316_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalista',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
