# Generated by Django 3.0.5 on 2020-04-30 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0003_auto_20200425_1135'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_doc', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Documento')),
                ('valor_emprestado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Emprestado')),
                ('qtd_parcelas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd Parcelas')),
                ('valor_prestacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da prestação')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('funcionario',),
            },
        ),
    ]
