# Generated by Django 3.0.5 on 2020-05-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_auto_20200501_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Data do Emprestimo'),
        ),
    ]
