# Generated by Django 3.0.5 on 2020-05-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0005_auto_20200511_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='datetime'),
        ),
    ]
