# Generated by Django 3.0.5 on 2020-05-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0007_remove_emprestimo_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ('-data_emprestimo',)},
        ),
    ]
