# Generated by Django 3.0.6 on 2020-06-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0013_emprestimopagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimopagamento',
            name='data_pagamento',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data do Pagamento'),
        ),
    ]
