# Generated by Django 3.0.6 on 2020-06-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0014_emprestimopagamento_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimopagamento',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
    ]
