# Generated by Django 3.0.6 on 2020-06-11 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0017_auto_20200611_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='funcionario',
        ),
    ]
