# Generated by Django 3.0.7 on 2020-07-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0004_auto_20200711_1739'),
        ('emprestimo', '0019_emprestimo_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='cliente_cnpj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente_cnpj.Cliente_cnpj'),
        ),
    ]
