# Generated by Django 3.0.7 on 2020-08-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0020_emprestimo_cliente_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_teste',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do teste'),
        ),
    ]
