# Generated by Django 3.0.7 on 2020-10-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0024_auto_20201002_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='num_doc',
        ),
    ]
