# Generated by Django 3.0.7 on 2020-10-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0025_remove_emprestimo_num_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_teste',
            field=models.DateField(blank=True, null=True, verbose_name='Data Teste'),
        ),
    ]
