# Generated by Django 3.0.7 on 2020-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0028_auto_20201005_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='n_de_teste',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Nº de Teste'),
        ),
    ]
