# Generated by Django 3.0.7 on 2020-10-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0030_remove_emprestimo_n_de_teste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ('-dt_teste',)},
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_emprestimo',
        ),
    ]
