# Generated by Django 3.0.7 on 2020-10-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0031_auto_20201008_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ('-dt_emprestimo',)},
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='dt_teste',
            new_name='dt_emprestimo',
        ),
    ]
