# Generated by Django 3.0.7 on 2020-10-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0032_auto_20201008_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_emprestado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Emprestado'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_prestacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor da prestação'),
        ),
    ]
