# Generated by Django 3.0.7 on 2020-11-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0034_auto_20201009_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='valor_multa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Multa por atraso'),
        ),
    ]
