# Generated by Django 3.0.7 on 2020-11-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0035_emprestimo_valor_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='juros_ao_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Juros ao dia'),
        ),
    ]
