# Generated by Django 3.0.7 on 2020-11-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0036_emprestimo_juros_ao_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='valor_mutuado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mutuado'),
        ),
    ]
