# Generated by Django 3.0.7 on 2020-11-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0039_taxa'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxa',
            name='taxa_juros_a_m2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Taxa de Juros a.m2'),
        ),
    ]
