# Generated by Django 3.0.7 on 2020-11-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0040_taxa_taxa_juros_a_m2'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='taxa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emprestimo.Taxa'),
        ),
    ]
