# Generated by Django 3.0.7 on 2020-11-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0041_emprestimo_taxa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='taxa',
        ),
        migrations.DeleteModel(
            name='Taxa',
        ),
    ]
