# Generated by Django 3.0.7 on 2020-11-10 19:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0043_emprestimo_juros_ao_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='juros_ao_mes',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('14.44'), max_digits=10, null=True, verbose_name='Juros ao mês'),
        ),
    ]
