# Generated by Django 3.0.7 on 2020-11-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0046_auto_20201110_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='juros_moratorio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Juros Moratório'),
        ),
    ]
