# Generated by Django 3.0.7 on 2020-11-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0047_emprestimo_juros_moratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='juros_moratorio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Juros Moratório'),
        ),
    ]
