# Generated by Django 3.0.7 on 2020-11-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0048_auto_20201113_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='multa_atrsado',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Multa por atraso'),
        ),
    ]
