# Generated by Django 3.0.7 on 2020-11-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0049_emprestimo_multa_atrsado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='multa_atrsado',
            new_name='multa_atrasado',
        ),
    ]
