# Generated by Django 3.0.7 on 2020-11-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0050_auto_20201113_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='multa_atrasado',
            new_name='multa_por_atraso',
        ),
    ]
