# Generated by Django 3.0.7 on 2020-11-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0051_auto_20201113_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='multa_por_atraso',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Multa por atraso'),
        ),
    ]
