# Generated by Django 3.0.7 on 2020-11-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0053_auto_20201113_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='iof_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IOF real'),
        ),
    ]
