# Generated by Django 3.0.7 on 2020-12-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0055_emprestimo_valor_devido'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='janeiro',
            field=models.BooleanField(default=True, verbose_name='janeiro'),
        ),
    ]
