# Generated by Django 3.0.7 on 2020-12-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0057_auto_20201224_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='primeiro',
        ),
    ]
