# Generated by Django 3.0.7 on 2021-02-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0058_remove_emprestimo_primeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='postergar',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Postergar'),
        ),
    ]
