# Generated by Django 3.0.7 on 2021-02-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0059_emprestimo_postergar'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='dt_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Vencimento'),
        ),
    ]
