# Generated by Django 3.0.7 on 2022-04-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0060_emprestimo_dt_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='onlene',
            field=models.BooleanField(default=False, verbose_name='Online'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='presencial',
            field=models.BooleanField(default=False, verbose_name='Presencial'),
        ),
    ]
