# Generated by Django 3.0.7 on 2022-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0063_emprestimo_sequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Registrado em'),
        ),
    ]
