# Generated by Django 3.0.7 on 2022-05-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0065_auto_20220521_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='n_contrato',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Nº Contrato'),
        ),
    ]
