# Generated by Django 3.0.7 on 2022-05-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0066_auto_20220521_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='sequencia',
            field=models.IntegerField(default=0, verbose_name='Sequencia'),
        ),
    ]
