# Generated by Django 3.0.7 on 2022-05-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0067_auto_20220524_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='sequencia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sequencia'),
        ),
    ]
