# Generated by Django 3.0.7 on 2022-05-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0068_emprestimo_sequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='renegociar',
            field=models.BooleanField(default=False, verbose_name='Renegociar'),
        ),
    ]
