# Generated by Django 3.0.7 on 2022-05-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0069_emprestimo_renegociar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='renegociar',
            field=models.BooleanField(default=False, verbose_name='Renegociação'),
        ),
    ]
