# Generated by Django 3.0.7 on 2022-06-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0070_auto_20220528_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_devido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True, verbose_name='Valor devido'),
        ),
    ]
