# Generated by Django 3.0.7 on 2022-06-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0071_auto_20220614_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='iof_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='IOF real'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='juros_ao_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Juros ao dia'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='juros_ao_mes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Juros ao mês'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='juros_moratorio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=50, null=True, verbose_name='Juros Moratório'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='multa_por_atraso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True, verbose_name='Multa por atraso'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_devido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor devido'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_emprestado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor Emprestado'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_multa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Multa por atraso'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_mutuado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor mutuado'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_prestacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Valor da parcela'),
        ),
    ]
