# Generated by Django 4.1.3 on 2023-07-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0073_alter_emprestimo_id_alter_emprestimopagamento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_mutuado',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True, verbose_name='Valor mutuado'),
        ),
    ]
