# Generated by Django 3.0.7 on 2020-09-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados_bancarios',
            options={'ordering': ('banco',)},
        ),
    ]
