# Generated by Django 3.0.7 on 2020-09-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dados_bancarios_tipo_de_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(blank=True, max_length=25, null=True, verbose_name='Banco')),
            ],
            options={
                'ordering': ('banco',),
            },
        ),
        migrations.CreateModel(
            name='Tipo_de_conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_conta', models.CharField(blank=True, max_length=25, null=True, verbose_name='tipo_de_conta')),
            ],
            options={
                'ordering': ('tipo_de_conta',),
            },
        ),
    ]
