# Generated by Django 3.0.7 on 2020-09-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_cnpj', '0037_auto_20200910_1211'),
        ('core', '0004_banco_tipo_de_conta'),
        ('cliente', '0048_auto_20200910_1211'),
        ('avalista', '0019_auto_20200910_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dados_bancarios',
        ),
    ]
