# Generated by Django 3.0.7 on 2022-03-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_dados_bancarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave_PIX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_key_type', models.CharField(blank=True, choices=[('cfpcnpj', 'CPF ou CNPJ'), ('email', 'E-mail'), ('cellphone', 'Celular ou Telefone'), ('randonkey', 'Chave aleatória.')], max_length=30, null=True, verbose_name='Tipo de Chave')),
                ('pix_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix')),
            ],
            options={
                'ordering': ('pix_key',),
            },
        ),
    ]
