# Generated by Django 3.0.7 on 2022-03-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220315_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chave_pix',
            options={'ordering': ('pix_key_type',)},
        ),
        migrations.RemoveField(
            model_name='chave_pix',
            name='pix_key',
        ),
    ]
