# Generated by Django 3.0.7 on 2022-03-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220315_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chave_pix',
            options={'ordering': ('pix_key_type',), 'verbose_name': 'Tipo de Chave PIX', 'verbose_name_plural': 'Tipo de Chave PIX'},
        ),
        migrations.AlterField(
            model_name='chave_pix',
            name='pix_key_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de Chave PIX'),
        ),
    ]
